manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    # Identique a la config Mechboards (MechboardsLTD/zmk-config, branche
    # refresh_mips), dont le firmware fait fonctionner nos ecrans.
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # Leur fork de nice-view-gem, pour eliminer aussi cette variable.
    - name: nv-gem
      url: https://github.com/MechboardsLTD/zmk-module
      revision: nv_gem
  self:
    path: config
